# this is a template to do docker build in Kubernetes
# Refer to my article https://medium.com/swlh/fast-docker-build-in-kubernetes-f52088854f45
apiVersion: v1
kind: Pod
metadata:
  name: docker-build
spec:
  volumes:
  - name: dind-storage
    emptyDir: {}
  containers:
  - name: docker
    image: docker:19.03.3-git
    command:
    - cat
    tty: true
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
  - name: dind
    image: docker:19.03.3-dind
    # alternatively use dind with git
    # image: baibai/docker:19.03.3-dind-git
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ''
    # Adjust the mtu value according to Kubernetes networking condition
    #args:
    #- "--mtu=1440"
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker